ignore_patterns = ["**/_*.mdx"]

[Rule001HeadingCase]
may_uppercase = [
    "[A-Z]{3,5}",
    "Android",
    "Angular",
    "Apple",
    "Auth",
    "Content Delivery Network",
    "Dart",
    "Edge Functions",
    "Flutter",
    "GoTrue",
    "Google",
    "GraphQL",
    "Ionic Angular",
    "Ionic React",
    "Ionic Vue",
    "JavaScript",
    "Kotlin",
    "Next.js",
    "Nuxt",
    "OpenAI",
    "Postgres",
    "PostgreSQL",
    "PostgREST",
    "React",
    "React Native",
    "RedwoodJS",
    "Row Level Security",
    "Server-Side Auth",
    "Single Sign-On",
    "SolidJS",
    "Supabase",
    "Svelte",
    "SvelteKit",
    "Swift",
    "SwiftUI",
    "Xcode",
    "Vue",
]
may_lowercase = []
